[package]
name = "aura-lsp"
edition.workspace = true
version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
aura-common.workspace = true
aura-salsa-db.workspace = true
aura-semantic.workspace = true
aura-ast.workspace = true
aura-fmt.workspace = true
async-lsp.workspace = true
lasso.workspace = true
salsa.workspace = true
tokio = { version = "1", features = ["rt", "io-std"] }
tokio-util = { version = "0.7", features = ["compat"] }
tower = "0.5"
tower-service = "0.3"
futures = "0.3"
serde_json = "1"
